### ISSUE TITLE
Broken step in SPENSER_HPC_setup.sh

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/spc-hpc-pipeline#7]
The SCP microsimulation has [4 consecutive steps](https://github.com/alan-turing-institute/spc-hpc-pipeline/blob/970bc417e58c33993b3d7dae7b12a9f110eaa836/scripts/scp/SPENSER_HPC_setup.sh#L137). Each step uses outputs from the previous one as inputs to to run.  The inputs/outputs are of each step are configured by [these json files](https://github.com/alan-turing-institute/spc-hpc-pipeline/tree/parallel/scripts/scp).

Currently, the 3rd step fails when running running for the first time: [line 145 of the SPENSER_HPC_setup.sh script](https://github.com/alan-turing-institute/spc-hpc-pipeline/blob/970bc417e58c33993b3d7dae7b12a9f110eaa836/scripts/scp/SPENSER_HPC_setup.sh#L145). However, if this step is run a second time the script finishes without error, creating the expected output and allowing for the final step to run. 

My suspicion is that there is confusion between the input/output files for the [run_ssm_h.py](https://github.com/nismod/microsimulation/blob/master/scripts/run_ssm_h.py) script which gets overwritten by the configuration file. Running twice is a hacky way of making work which is good enough for PR #6 but we need to understand what is going on and fix it either in the [microsimulation](https://github.com/nismod/microsimulation/) source code or convince ourselves that running it twice is ok (this step takes seconds so this is not an issue).

**Comment by crangelsmith** [comment]
Fail error is the following, and is happening in [this line](https://github.com/nismod/microsimulation/blob/37ce2843f10b83a8e7a225c801cec83b85e6e0d0/microsimulation/static_h.py#L54) of the source code.

```
Traceback (most recent call last):
  File "/mnt/batch/tasks/workitems/SPCCamilaJob/job-1/Task0_E06000001/wd/miniconda/envs/spc_env/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 391, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/batch/tasks/workitems/SPCCamilaJob/job-1/Task0_E06000001/wd/microsimulation/scripts/run_ssm_h.py", line 47, in <module>
    main(params)
  File "/mnt/batch/tasks/workitems/SPCCamilaJob/job-1/Task0_E06000001/wd/microsimulation/scripts/run_ssm_h.py", line 37, in main
    ssm.run(ref_year, horizon_year)
  File "/mnt/batch/tasks/workitems/SPCCamilaJob/job-1/Task0_E06000001/wd/miniconda/envs/spc_env/lib/python3.9/site-packages/microsimulation-0.0.1-py3.9.egg/microsimulation/static_h.py", line 54, in run
    basepop = int(self.__get_snhp(base_year))
  File "/mnt/batch/tasks/workitems/SPCCamilaJob/job-1/Task0_E06000001/wd/miniconda/envs/spc_env/lib/python3.9/site-packages/microsimulation-0.0.1-py3.9.egg/microsimulation/static_h.py", line 135, in __get_snhp
    return self.snhpdata.aggregate(self.region, year).OBS_VALUE[0]
  File "/mnt/batch/tasks/workitems/SPCCamilaJob/job-1/Task0_E06000001/wd/miniconda/envs/spc_env/lib/python3.9/site-packages/pandas/core/series.py", line 981, in __getitem__
    return self._get_value(key)
  File "/mnt/batch/tasks/workitems/SPCCamilaJob/job-1/Task0_E06000001/wd/miniconda/envs/spc_env/lib/python3.9/site-packages/pandas/core/series.py", line 1089, in _get_value
    loc = self.index.get_loc(label)
  File "/mnt/batch/tasks/workitems/SPCCamilaJob/job-1/Task0_E06000001/wd/miniconda/envs/spc_env/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 393, in get_loc
    raise KeyError(key) from err
KeyError: 0
```
